### ISSUE TITLE
Learn Async Await

### ISSUE THREAD

**Issue by tanishqvyas** [cybraia/LearnReact#1]
Learn about async-await in javascript and write small code snippets to understand the same.

**Comment by cybraia** [comment]
de2f8a36ef4f8dade23c8598cc6260abf10912fd

**Comment by cybraia** [comment]
commit dd4e617621dc459efbbb30c3fd639559e90e605f

**Comment by cybraia** [comment]
commit  de2f8a36ef4f8dade23c8598cc6260abf10912fd

**Comment by cybraia** [comment]
commit de2f8a36ef4f8dade23c8598cc6260abf10912fd
